version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    groups:
      security:
        patterns:
          - "*"
        update-types:
          - "security"
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-actions:
        patterns: ["*"]
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
