"""Tests for the docker-compose.yml — two-service configuration (server + neo4j).

TDD phase: These tests define the EXPECTED state after removing the init service
(Task 1), which:
  - Removes the `init` service entirely (credentials are now generated by start.sh on the host)
  - Removes `depends_on: init` from both context-intelligence-server and neo4j
  - Keeps context-intelligence-server depending only on neo4j being healthy
  - Keeps everything else unchanged
"""

import pathlib

import yaml

PROJECT_ROOT = pathlib.Path(__file__).parent.parent
COMPOSE_FILE = PROJECT_ROOT / "docker-compose.yml"


def _compose() -> dict:
    return yaml.safe_load(COMPOSE_FILE.read_text())


def test_valid_yaml() -> None:
    """docker-compose.yml must be valid YAML."""
    content = COMPOSE_FILE.read_text()
    parsed = yaml.safe_load(content)
    assert isinstance(parsed, dict), "docker-compose.yml must parse to a dict"
    assert "services" in parsed, "docker-compose.yml must have a 'services' key"


def test_exactly_two_services() -> None:
    """docker-compose.yml must contain exactly 2 services: server and neo4j (no init)."""
    services = _compose().get("services", {})
    assert list(services.keys()) == ["context-intelligence-server", "neo4j"], (
        f"Expected exactly ['context-intelligence-server', 'neo4j'], got {list(services.keys())}"
    )


def test_no_init_service() -> None:
    """init service must NOT be present in docker-compose.yml."""
    services = _compose().get("services", {})
    assert "init" not in services, (
        "init service must NOT be present — credentials are now generated by start.sh on the host"
    )


def test_no_intelligence_service_or_frontend() -> None:
    """intelligence-service and frontend must not be present."""
    services = _compose().get("services", {})
    assert "intelligence-service" not in services, (
        "intelligence-service must not be present in docker-compose.yml"
    )
    assert "frontend" not in services, (
        "frontend must not be present in docker-compose.yml"
    )


def test_no_neo4j_auth_none() -> None:
    """NEO4J_AUTH: none must NOT be present anywhere in docker-compose.yml."""
    raw = COMPOSE_FILE.read_text()
    assert "NEO4J_AUTH: none" not in raw, (
        "NEO4J_AUTH: none must be removed — auth is now managed via generated env_file"
    )
    # Also check parsed form
    compose = _compose()
    neo4j_env = (
        compose.get("services", {}).get("neo4j", {}).get("environment", {}) or {}
    )
    assert "NEO4J_AUTH" not in neo4j_env, (
        "NEO4J_AUTH must not appear in neo4j environment dict"
    )


def test_server_depends_on_only_neo4j() -> None:
    """context-intelligence-server must depend only on neo4j (not init)."""
    server = _compose()["services"]["context-intelligence-server"]
    depends_on = server.get("depends_on", {})
    assert "init" not in depends_on, (
        "context-intelligence-server must NOT depend on init — init service removed"
    )
    assert "neo4j" in depends_on, "context-intelligence-server must depend on neo4j"
    assert depends_on["neo4j"].get("condition") == "service_healthy", (
        "context-intelligence-server must depend on neo4j with service_healthy"
    )


def test_neo4j_has_no_depends_on_init() -> None:
    """neo4j must NOT have depends_on: init."""
    neo4j = _compose()["services"]["neo4j"]
    depends_on = neo4j.get("depends_on", {})
    assert "init" not in depends_on, (
        "neo4j must NOT depend on init — init service removed"
    )


def test_neo4j_uses_env_file() -> None:
    """neo4j must use env_file for auth credentials (not inline environment)."""
    neo4j = _compose()["services"]["neo4j"]
    env_file = neo4j.get("env_file")
    assert env_file is not None, "neo4j must have an env_file for auth credentials"


def test_server_has_config_file_env() -> None:
    """context-intelligence-server must have AMPLIFIER_CONTEXT_INTELLIGENCE_SERVER_CONFIG_FILE set."""
    server = _compose()["services"]["context-intelligence-server"]
    env = server.get("environment", {})
    assert "AMPLIFIER_CONTEXT_INTELLIGENCE_SERVER_CONFIG_FILE" in env, (
        "server must have AMPLIFIER_CONTEXT_INTELLIGENCE_SERVER_CONFIG_FILE env var"
    )
    assert (
        env["AMPLIFIER_CONTEXT_INTELLIGENCE_SERVER_CONFIG_FILE"]
        == "/data/credentials.yaml"
    ), (
        "AMPLIFIER_CONTEXT_INTELLIGENCE_SERVER_CONFIG_FILE must be /data/credentials.yaml"
    )
