"""Static guards for the Docker infrastructure.

These are the two checks that earn their place as *fast, blocking* unit tests
because they encode real contracts a text scan can meaningfully protect:

  1. The base image must be a Python >= 3.11 image (the project's requires-python
     floor) — a capability, parsed from the FROM line, not a hardcoded string.
  2. Neo4j credentials must NOT be inlined in docker-compose.yml — a security
     policy (auth comes from a generated env_file).

The rest of the old suite string-matched the Dockerfile / compose file
("WORKDIR /app" in content, "curl" in content, …). Those proved only that a text
file contains substrings — they broke on legitimate changes (false red) and
passed while the image was actually broken (false green). Real behaviour — the
image builds, boots, and serves — is now proven for real in
``tests/integration/test_docker_image.py`` (build + run + curl /status).
"""

import pathlib
import re

import pytest
import yaml

PROJECT_ROOT = pathlib.Path(__file__).parent.parent
DOCKERFILE = PROJECT_ROOT / "Dockerfile"
COMPOSE_FILE = PROJECT_ROOT / "docker-compose.yml"


# ---------------------------------------------------------------------------
# Dockerfile: base-image capability (not a hardcoded image string)
# ---------------------------------------------------------------------------


def test_dockerfile_base_image() -> None:
    """The base image must be a Python image at a version the project supports.

    Verifies a capability (a Python >= 3.11 base, per requires-python) rather than
    a hardcoded image string, so the base can change for security or platform
    reasons (e.g. Azure Linux) without breaking this test.
    """
    content = DOCKERFILE.read_text()

    from_lines = [
        line.strip()
        for line in content.splitlines()
        if line.strip().upper().startswith("FROM ")
    ]
    assert from_lines, "Dockerfile must declare a base image with FROM"

    base = from_lines[0].lower()
    assert "python" in base, f"Base image must be a Python image, got: {from_lines[0]}"

    match = re.search(r"python[:/].*?(\d+)\.(\d+)", base)
    assert match, f"Could not determine Python version from base image: {from_lines[0]}"

    major, minor = int(match.group(1)), int(match.group(2))
    assert (major, minor) >= (3, 11), (
        f"Base image Python must be >= 3.11 (requires-python), got {major}.{minor}"
    )


# ---------------------------------------------------------------------------
# docker-compose.yml: security policy (no inline Neo4j credentials)
# ---------------------------------------------------------------------------


@pytest.fixture
def compose() -> dict:
    """Parse docker-compose.yml and return as dict."""
    return yaml.safe_load(COMPOSE_FILE.read_text())


def test_compose_neo4j_auth_env(compose: dict) -> None:
    """Neo4j auth is provided via env_file (generated by init), not inline env vars.

    NEO4J_AUTH must NOT appear in the inline environment block — it comes from
    the generated neo4j-auth.env file so credentials can be securely created at
    container start rather than hardcoded in the compose file.
    """
    neo4j = compose["services"]["neo4j"]
    env = neo4j.get("environment", {}) or {}
    if isinstance(env, list):
        env_str = "\n".join(env)
        assert "NEO4J_AUTH" not in env_str, (
            "NEO4J_AUTH must not be set inline — use env_file for auth credentials"
        )
    else:
        assert "NEO4J_AUTH" not in env, (
            "NEO4J_AUTH must not be set inline — use env_file for auth credentials"
        )
    # Auth is provided via env_file instead
    assert neo4j.get("env_file") is not None, (
        "neo4j must use env_file for auth credentials"
    )
