#!/usr/bin/env python3
"""Prime a local (non-Docker) config for the Context Intelligence Server.

This replaces the credential bootstrap that the Docker entrypoint used to do
(it wrote ``/data/credentials.yaml`` on first run) for developers running the
server **directly on their machine**, without Docker.

It:
  * generates an API token, prints it ONCE, and stores only its SHA-256 digest
    (the server authenticates by digest — the raw token is never persisted);
  * sets up the Neo4j password (generated unless you pass one);
  * points storage at a **local writable directory** (not the container's
    ``/data``, which is not writable on a normal machine);
  * writes a ``server-config.yaml`` the server reads on startup.

Usage:
    python scripts/prime-local-config.py                    # generate everything
    python scripts/prime-local-config.py --neo4j-password mypass
    python scripts/prime-local-config.py --data-dir ~/.context-intelligence
    python scripts/prime-local-config.py --force            # overwrite existing

Stdlib only — runs with any python3, no virtualenv required.
"""

from __future__ import annotations

import argparse
import hashlib
import secrets
import stat
import sys
from pathlib import Path


def _gen_secret() -> str:
    """A URL-safe secret, matching the Docker entrypoint's generator."""
    return secrets.token_urlsafe(32)


def _sha256_hex(value: str) -> str:
    return hashlib.sha256(value.encode()).hexdigest()


def _yaml_escape(value: str) -> str:
    """Double-quote a scalar for YAML and escape embedded quotes/backslashes."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def build_config(
    *,
    neo4j_url: str,
    neo4j_user: str,
    neo4j_password: str,
    api_key_digest: str,
    data_dir: Path,
    server_host: str,
    server_port: int,
) -> str:
    """Render a minimal, correct server-config.yaml for a local static-auth run."""
    blobs = data_dir / "blobs"
    queues = data_dir / "queues"
    logs = data_dir / "logs" / "server.jsonl"
    identity = data_dir / "identity" / "api-keys.json"
    return f"""# Local dev config for the Context Intelligence Server.
# Generated by scripts/prime-local-config.py — safe to edit by hand.
# Resolution order is env > this file > built-in defaults.

# --- Neo4j (local, single instance) ---
# Use bolt:// (NOT neo4j://) for a Community single-node install.
neo4j_url: {_yaml_escape(neo4j_url)}
neo4j_user: {_yaml_escape(neo4j_user)}
neo4j_password: {_yaml_escape(neo4j_password)}

# --- Auth (static mode) ---
# The server authenticates by SHA-256 digest; the raw token is NOT stored here.
api_keys:
  {_yaml_escape(api_key_digest)}:
    id: owner
# Where runtime-added keys persist (must be a writable path).
api_keys_store_path: {_yaml_escape(str(identity))}

# --- Storage (local writable paths, not the container's /data) ---
blob_path: {_yaml_escape(str(blobs))}
queues_path: {_yaml_escape(str(queues))}
log_path: {_yaml_escape(str(logs))}

# --- Server bind ---
server_host: {_yaml_escape(server_host)}
server_port: {server_port}
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Prime a local (non-Docker) config for the Context Intelligence Server.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--config-path",
        type=Path,
        default=Path("server-config.yaml"),
        help="Where to write the config (default: ./server-config.yaml).",
    )
    parser.add_argument(
        "--data-dir",
        type=Path,
        default=Path(".context-intelligence-data"),
        help="Local writable dir for blobs/queues/logs/identity "
        "(default: ./.context-intelligence-data).",
    )
    parser.add_argument(
        "--neo4j-url",
        default="bolt://localhost:7687",
        help="Neo4j Bolt URL (default: bolt://localhost:7687).",
    )
    parser.add_argument(
        "--neo4j-user", default="neo4j", help="Neo4j user (default: neo4j)."
    )
    parser.add_argument(
        "--neo4j-password",
        default=None,
        help="Neo4j password. If omitted, one is generated and printed "
        "(you must then set it on your Neo4j instance).",
    )
    parser.add_argument(
        "--server-host", default="127.0.0.1", help="Bind host (default: 127.0.0.1)."
    )
    parser.add_argument(
        "--server-port", type=int, default=8000, help="Bind port (default: 8000)."
    )
    parser.add_argument(
        "--force", action="store_true", help="Overwrite an existing config file."
    )
    args = parser.parse_args(argv)

    config_path: Path = args.config_path
    if config_path.exists() and not args.force:
        print(
            f"Refusing to overwrite existing {config_path} (pass --force to replace it).",
            file=sys.stderr,
        )
        return 1

    data_dir: Path = args.data_dir.expanduser().resolve()

    # Generate credentials.
    raw_token = _gen_secret()
    api_key_digest = _sha256_hex(raw_token)
    neo4j_password_generated = args.neo4j_password is None
    neo4j_password = args.neo4j_password or _gen_secret()

    # Create the local writable storage tree.
    for sub in ("blobs", "queues", "logs", "identity"):
        (data_dir / sub).mkdir(parents=True, exist_ok=True)

    # Write the config, locked down to the owner.
    config_text = build_config(
        neo4j_url=args.neo4j_url,
        neo4j_user=args.neo4j_user,
        neo4j_password=neo4j_password,
        api_key_digest=api_key_digest,
        data_dir=data_dir,
        server_host=args.server_host,
        server_port=args.server_port,
    )
    config_path.write_text(config_text)
    try:
        config_path.chmod(stat.S_IRUSR | stat.S_IWUSR)  # 0600
    except OSError:
        pass  # best-effort (e.g. on filesystems without POSIX perms)

    # Report — token printed ONCE.
    line = "=" * 60
    print(f"Wrote {config_path}")
    print(f"Local data dir: {data_dir}")
    print()
    print(line)
    print("  SAVE THIS API TOKEN — it will NOT be shown again.")
    print("  The config stores only its SHA-256 digest, not the token.")
    print()
    print(f"  API token: {raw_token}")
    if neo4j_password_generated:
        print()
        print("  Neo4j password (generated) — set this on your Neo4j instance,")
        print("  e.g.  neo4j-admin dbms set-initial-password '<password>' :")
        print(f"  Neo4j password: {neo4j_password}")
    print(line)
    print()
    print("Next: start Neo4j (bolt://localhost:7687) with the password above,")
    print(
        f"then run the server with AMPLIFIER_CONTEXT_INTELLIGENCE_SERVER_CONFIG_FILE={config_path}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
